# global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
 alertmanagers:
 - static_configs:
   - targets: [127.0.0.1:9093]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'skycloud-actuator'
    tls_config:
      insecure_skip_verify: false
    metrics_path: '/monitor/prometheus'
    scrape_interval: 5s
    scheme: http
    params:
      format: ['prometheus']
    consul_sd_configs:
      - server: '127.0.0.1:8500'
        scheme: http
        services: [member,skycloud-base-gateway,authorization]
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        target_label: 'service'
        #regex: 正则规则
        #action: keep
    

  - job_name: mysql
    static_configs:
      - targets: ['127.0.0.1:9104']
        labels:
          instance: DB1
#可将static_configs替换成文件形式
    #file_sd_configs:
    #  - files:
    #     - xxx.yml
